daemon:
    tty: true
    build: ./
    command: python run.py
    net: "host"
    ports:
        - "8888:8888"
    volumes:
        - .:/root/daemon
        - /tmp:/tmp
        - /var/log:/var/log


